### ISSUE TITLE
python_actr does not work on python 3.11+

### ISSUE THREAD

**Issue by asmaloney** [asmaloney/gactar#310]
Trying to run a model using python 3.11+ will produce the following error in python_actr:

```
ccm
---
error: execution failed:
Traceback (most recent call last):
  File "/.../env/gactar-temp/ccm_semantic.py", line 62, in <module>
    log_everything(model)
  File "/.../env/lib/python3.11/site-packages/python_actr/model.py", line 36, in log_everything
    if not hasattr(model,'log'): model.run(limit=0)
                                 ^^^^^^^^^^^^^^^^^^
  File "/.../env/lib/python3.11/site-packages/python_actr/model.py", line 241, in run
    self.__convert()
  File "/.../env/lib/python3.11/site-packages/python_actr/model.py", line 133, in __convert
    self._convert_info(objects,methods)
  File "/.../env/lib/python3.11/site-packages/python_actr/production.py", line 61, in _convert_info
    a,va,hk,d=inspect.getargspec(v)
              ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?
end...
```

Not much I can do here since we use pip to install python_actr now instead of maintaining a fork.

The problem has [been reported](https://github.com/CarletonCognitiveModelingLab/python_actr/issues/19) and a [fix exists](https://github.com/asmaloney/CCM-PyACTR/commit/094d881a287adb28e753091bdaacc1a8e82b116b) for at least one of the issues.

**Comment by asmaloney** [comment]
[My python_actr fork](https://github.com/asmaloney/python_actr) works on gactar's examples with Python 3.11.

If the original version isn't fixed by the time I'm ready to do another release, I will use my fork instead.
